corpe/predict/routes.py
from flask import (Flask, render_template, flash, Blueprint,
                   current_app, url_for, request, redirect,
                   make_response, session, abort)
from corpe import db
from corpe.models import Dataset
from corpe.predict.forms import PredictForm
from corpe.predict.knn import knn
import csv

# create blueprint
predict_bp = Blueprint('predict', __name__)

# route to generate dataset into database


@predict_bp.route('/gen-ds')
def generate_dataset():
    """ Endpoint to create datasets"""
    # if dataset was created
    if len(Dataset.query.all()) >= 303:
        # abort to 404
        abort(404)
    with open(current_app.instance_path+'/heart.csv', newline='') as csvfile:
        # read csv file
        heart_csv = csv.reader(csvfile)
        # skip the first row which a variable name
        next(heart_csv)
        # loop and add to session
        for row in heart_csv:
            data = Dataset(age=row[0], sex=row[1], cp=row[2], trestbps=row[3], chol=row[4],
                           fbs=row[5], restecg=row[6], thalach=row[7], exang=row[8], oldpeak=row[9],
                           slope=row[10], ca=row[11], thal=row[12], target=row[13])
            db.session.add(data)
    # commit and show basic response
    db.session.commit()
    return make_response('Dataset created')

# route to heart dissease prediction


@predict_bp.route('/predict', methods=['GET', 'POST'])
def predict():
    """
    this function to get data and then post the data processing knn
    """
    # create instance PredictForm
    form = PredictForm()
    # form successful submitted
    if form.validate_on_submit():
        # load data on an array 'data'
        data = [form.age.data, form.sex.data, form.cp.data, form.trestbps.data,
                form.chol.data, form.fbs.data, form.restecg.data, form.thalach.data,
                form.exang.data, form.oldpeak.data, form.slope.data, form.ca.data, form.thal.data]
        # predict using knn module and get target result assign to 'result'
        result = knn(data)
        # dummy data
        # row = [572,1,1,154,232,0,0,164,0,0,2,1,2]
        # process to database
        ds = Dataset(age=data[0], sex=data[1], cp=data[2], trestbps=data[3], chol=data[4],
                     fbs=data[5], restecg=data[6], thalach=data[7], exang=data[8], oldpeak=data[9],
                     slope=data[10], ca=data[11], thal=data[12], target=str(result))
        db.session.add(ds)
        db.session.commit()
        session['predicted'] = ds.id
        # flash message and redirect to result page
        flash('Hore', 'success')
        # return redirect(url_for('predict.predicted', id=ds.id))
        return redirect(url_for('predict.result'))
    # route get
    return render_template('predict/predict.html', title='Cek', form=form)


@predict_bp.route('/predict/result')
def result():
    """
    show result of prediction
    """
    # catch error if session['predicted'] unset
    try:
        # get data by id(session['predicted'])
        result = Dataset.query.get(session['predicted'])
    except Exception as e:
        # redirect to home page
        return redirect(url_for('main.index'))
    return render_template('predict/result.html', title='Hasil', data=result)

corpe/templates/main/about.html
{% extends "layouts/base-sub.html" %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<section id="main" class="wrapper">
	<div class="inner">
		<header class="align-center">
			<h2>Tentang</h2>
			<p>Sekilas tentang</p>
		</header>

		<!-- Intro -->
		<div class="row">
			<section class="6u 12u$(medium)">
				<h2>Sistem Prediksi</h2>
				<p>
					Sistem prediksi penyakit jantung koroner berbasis website ini dibangun guna membangun kesadaran
					kesehatan jantung dan melakukan pencegahan dini serta segera melakukan perawatan jika terindikasi
					memiliki penyakit jantung
				</p>
			</section>
			<section class="6u 12u$(medium)">
				<h2>Untuk</h2>
				<ul class="alt">
					<li>Masyarakat umum</li>
					<li>Dokter</li>
					<li>Mahasiswa kedokteran</li>
				</ul>
			</section>
		</div>
	</div>

	</div>

</section>
{% endblock %}

corpe/templates/main/guide.html
{% extends "layouts/base-sub.html" %}
{% block title %} {{ title }} {% endblock %}

{% block content %}
<!-- Main -->
<section id="main" class="wrapper">
    <div class="inner">
        <header class="align-center">
            <h2>Petunjuk penggunaan</h2>
            <p>Penggunaan aplikasi prediksi penyakit jantung koroner</p>
        </header>

        <!-- Intro -->
        <div class="row">
            <section class="6u 12u$(medium)">
                <h2>Bagaimana?</h2>
                <p><strong>Pengguna</strong> harus mengisikan data kesehatan yang dimiliki melalui form pada <a
                        href="{{ url_for('predict.predict') }}">Halaman ini</a>. Data yang diisikan haruslah benar dan
                    tepat agar
                    didapatkan hasil prediksi yang baik. Detail pengisian ada di bawah ini.</p>
            </section>
            <section class="6u 12u$(medium) ">
                <h3>Informasi</h3>
                <p>Data kesehatan yang dimasukkan akan disimpan di basis data sistem untuk pengembangan
                    akurasi sistem prediksi tanpa menyebarluaskan data dan identitas pemilik data.</p>
            </section>
        </div>

        <hr class="major" />
        <h4>Data yang dimasukkan</h4>
        <dl>
            <dt>Usia</dt>
            <dd>
                <p>Usia pasien saat memasukkan data.</p>
            </dd>
            <dt>Jenis kelamin</dt>
            <dd>
                <p>Jenis kelamin pasien, laki-laki/perempuan.</p>
            </dd>
            <dt>Jenis nyeri pada dada</dt>
            <dd>
                <p>Jenis nyeri pada dada. <strong>Angina</strong> adalah jenis nyeri
                    pada dada ketika otot dada tidak mendapat cukup oksigen.</p>
            </dd>
            <dt>Tekanan darah istirahat saat istirahat</dt>
            <dd>
                <p>Tekanan darah pasien ketika tidak beraktifitas
                    atau dalam masa istirahat.</p>
            </dd>
            <dt>Kolesterol dalam mg/dl</dt>
            <dd>
                <p>Kadar kolesterol dalam satuan miligram per desiliter</p>
            </dd>
            <dt>Kadar gula darah > 120 mg/dl</dt>
            <dd>
                <p>Kadar gula darah, jika lebih dari 120 mg/dl.</p>
            </dd>
            <dt>Hasil tes elektrokardiografi saat istirahat</dt>
            <dd>
                <p>Hasil tes
                    elektrokardiografi ketika pasien istirahat.</p>
            </dd>
            <dt>Hasil tes elektrokardiografi saat istirahat</dt>
            <dd>
                <p>Hasil tes
                    elektrokardiografi ketika pasien istirahat.</p>
                <ul class="alt">
                    <li>Normal.</li>
                    <li>Having ST-T: Memiliki kelainan gelombang ST-T
                        (inversi gelmbang T dan elevasi atau depresi ST > 0.05 mV).</li>
                    <li>Menunjukkan hipertrofi ventrikel kiri yang mungkin atau
                        pasti dengan kriteria estes.</li>
                </ul>
            </dd>
            <dt>Denyut jantung maksimum.</dt>
            <dd>
                <p>Denyut jantung maksimum yang dicapai pasien.</p>
            </dd>
            <dt>Nyeri saat beraktifitas.</dt>
            <dd>
                <p>Nyeri yang dialami pasien saat berolahraga.</p>
            </dd>
            <dt>Depresi ST saat beraktifitas.</dt>
            <dd>
                <p>Penurunan ST saat beraktifitas dalam nilai desimal. ST adalah.</p>
            </dd>
            <dt>Kemiringan puncak ST saat beraktifitas</dt>
            <dd>
                <p>Kemiringan puncak ST saat beraktifitas</p>
                <ul class="alt">
                    <li>Upsloping: menanjak.</li>
                    <li>Flat: datar.</li>
                    <li>Downsloping: miring ke bawah.</li>
                </ul>
            </dd>
            <dt>Pembuluh darah terdeteksi</dt>
            <dd>
                <p>Banyaknya pembuluh darah yang diwarnai
                    melalui Fluoroscopy</p>
            </dd>
            <dt>Pemeriksaan thalassemia</dt>
            <dd>
                <p></p>
                <ul class="alt">
                    <li>Normal: normal.</li>
                    <li>Fixed Defect: cacat tetap.</li>
                    <li>Reversable Defect: cacat yang dapat dikembalikkan.</li>
                </ul>
            </dd>
        </dl>
    </div>

</section>
{% endblock %}

corpe/templates/main/heart.html
{% extends "layouts/base-sub.html" %}
{% block title %} {{ title }} {% endblock %}

{% block content %}
<!-- Main -->
<section id="main" class="wrapper">
    <div class="inner">
        <header class="align-center">
            <h2>Penyakit jantung koroner</h2>
            <p>Informasi tentang penyakit jantung koroner</p>
        </header>

        <!-- Content -->
        <h2 id="content">Penyakit Jantung</h2>
        <p>
            Penyakit jantung adalah kondisi ketika jantung mengalami gangguan. Bentuk gangguan itu sendiri bisa
            bermacam-macam. Ada gangguan pada pembuluh darah jantung, irama jantung, katup jantung, atau gangguan
            akibat bawaan lahir.
        </p>
        <p>
            Jantung adalah otot yang terbagi menjadi empat ruang. Dua ruang terletak di bagian atas, yaitu atrium
            (serambi) kanan dan kiri. Sedangkan dua ruang lagi terletak di bagian bawah, yaitu ventrikel (bilik)
            kanan dan kiri. Antara ruang kanan dan kiri dipisahkan oleh dinding otot (septum) yang berfungsi
            mencegah tercampurnya darah yang kaya oksigen dengan darah yang miskin oksigen.
        </p>
        <p>Sumber: <a href="https://www.alodokter.com/penyakit-jantung">Aldodokter</a></p>
        <div class="row">
            <div class="6u 12u$(small)">
                <h3>Jenis penyakit jantung</h3>
                <p>
                    Ada beberapa jenis penyakit jantung, antara lain
                </p>
                <dl>
                    <dt>Penyakit jantung koroner</dt>
                    <dd>
                        <p>Merupakan suatu penyakit jantung yang terjadi akibat penyempitan pembuluh darah di jantung.</p>
                    </dd>
                    <dt>Penyakit jantung bawaan</dt>
                    <dd>
                        <p>Penyakit jantung bawaan, merupakan suatu masalah jantung yang ditemukan sejak bayi, yang paling umum ditemukan adalah kebocoran katup jantung.</p>
                    </dd>
                    <dt>Infeksi jantung (endokarditis)</dt>
                    <dd>
                        <p>Infeksi jantung (endokarditis), merupakan suatu infeksi pada lapisan dalam jantung.
                            Gagal jantung, merupakan suatu kegagalan otot jantung untuk memompakan darah secara memadai ke seluruh tubuh.</p>
                    </dd>
                    <dt>Aritmia</dt>
                    <dd>
                        <p>Aritmia, merupakan suatu gangguan irama jantung yang menyebabkan denyut jantung tidak normal.</p>
                    </dd>
                </dl>
                <p>Sumber: <a href="https://www.halodoc.com/kesehatan/penyakit-jantung">Halodoc</a></p>
            </div>
            <div class="6u$ 12u$(small)">
                <h3>Pencegahan</h3>
                <p>Pada penyakit jantung bawaan, upaya pencegahan yang efektif belum ditemukan hingga saat ini. Namun demikian, pada penyakit jantung koroner, gagal jantung, dan aritmia, beberapa upaya pencegahan dapat dilakukan, antara lain:</p>
                <ul class="alt">
                    <li>Mengonsumsi makanan tinggi serat, rendah gula, dan rendah lemak.</li>
                    <li>Menghentikan kebiasaan merokok dan menghindari paparan asap rokok.</li>
                    <li>Memeriksa tekanan darah, gula darah, dan kolesterol secara berkala.</li>
                    <li>Melakukan latihan fisik, seperti jogging, bersepeda, dan berenang, setidaknya 30 menit setiap hari.</li>
                </ul>
                <p>Sumber: <a href="https://www.halodoc.com/kesehatan/penyakit-jantung">Halodoc</a></p>
            </div>

        </div>

    </div>

</section>
{% endblock %}

corpe/templates/main/index.html
<!DOCTYPE HTML>
<!--
	Projection by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>

<head>
	<title>{{ title }}</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<link rel="shortcut icon"
		href="https://www.freepngimg.com/download/heart/36704-5-dark-red-heart-transparent-background.png"
		type="image/x-icon">
	<link rel="stylesheet" href="/static/assets/css/main.css" />
	<link rel="stylesheet" type="text/css"
		href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
		.a-footer {
			color: #fff !important;
			text-decoration: none;
		}

		.icon-footer {
			color: #fff !important;
			font-size: 1em !important;
		}
	</style>
</head>

<body>

	<!-- Header -->
	<header id="header">
		<div class="inner">
			<a href="{{ url_for('main.index') }}" class="logo"><strong>KNN</strong> Heart Dissease</a>
			<nav id="nav">
				<a href="{{ url_for('main.index') }}">Bernada</a>
				<a href="{{ url_for('main.guide') }}">Petunjuk Penggunaan</a>
				<a href="{{ url_for('main.heart') }}">Jantung</a>
				<a href="{{ url_for('main.about') }}">Tentang</a>
			</nav>
			<a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
		</div>
	</header>

	<!-- Banner -->
	<section id="banner">
		<div class="inner">
			<header>
				<h1>Selamat datang</h1>
			</header>

			<div class="flex ">

				<div>
					<a href="{{ url_for('main.guide') }}" style="text-decoration: none;"><span
							class="icon fa-play"></span></a>
					<h3>Petunjuk</h3>
					<p>Penggunaan aplikasi</p>
				</div>

				<div>
					<a href="{{ url_for('main.heart') }}" style="text-decoration: none;"><span
							class="icon fa-heart"></span></a>
					<h3>Jantung Koroner</h3>
					<p>Sekilas tentang</p>
				</div>

				<div>
					<a href="{{ url_for('main.about') }}" style="text-decoration: none;"><span
							class="icon fa-address-card"></span></a>
					<h3>Profil</h3>
					<p>Profil aplikasi</p>
				</div>

			</div>

			<footer>
				<a href="{{ url_for('predict.predict') }}" class="button">Predict</a>
			</footer>
		</div>
	</section>
	<!-- Footer -->
	<footer id="footer">
		<div class="inner">

			<div class="row">
				<!-- Break -->
				<div class="4u 12u$(medium)">
					<h3>Get in touch</h3>
					<ul class="icons">
						<li><a href="https://twitter.com/chud_lori" class="icon icon-footer fa-twitter"><span
									class="label">Twitter</span></a></li>
						<li><a href="http://facebook.com/" class="icon icon-footer fa-facebook"><span
									class="label">Facebook</span></a></li>
						<li><a href="https://medium.com/@chud_lori" class="icon icon-footer fa-medium"><span
									class="label">Instagram</span></a></li>
						<li><a href="https://github.com/chud-lori" class="icon icon-footer fa-github"><span
									class="label">Github</span></a></li>
					</ul>
				</div>
				<div class="4u 12u$(medium)">
					<h3>Info</h3>
					<p>Sistem ini masih membutuhkan banyak peningkatan. Jika anda tertarik untuk
						melakukan peningkatan silakan pull request di <a class="a-footer"
							href="https://github.com/chud-lori/coronary-knn-flask">repository</a></p>
				</div>
				<div class="4u$ 12u$(medium)">
					<h3>Sitemap</h3>
					<ul class="alt">
						<li><a class="a-footer" href="/">Bernada</a></li>
						<li><a class="a-footer" href="/petunjuk">Petunjuk</a></li>
						<li><a class="a-footer" href="/koroner">Koroner</a></li>
						<li><a class="a-footer" href="/tentang">Tentang</a></li>
					</ul>
				</div>
			</div>

			<div class="copyright" style="display: none;">
				&copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a
					href="https://unsplash.com">Unsplash</a>.
			</div>

		</div>
	</footer>

	<!-- Scripts -->
	<script src="/static/assets/js/jquery.min.js"></script>
	<script src="/static/assets/js/skel.min.js"></script>
	<script src="/static/assets/js/util.js"></script>
	<script src="/static/assets/js/main.js"></script>

</body>

</html>

corpe/templates/main/jantung.html
{% extends "layouts/base-sub.html" %}
{% block title %} {{ title }} {% endblock %}

{% block content %}
<!-- Main -->
<section id="main" class="wrapper">
    <div class="inner">
        <header class="align-center">
            <h2>Penyakit jantung koroner</h2>
            <p>Informasi tentang penyakit jantung koroner</p>
        </header>

        <!-- Content -->
        <h2 id="content">Penyakit Jantung</h2>
        <p>
            Penyakit jantung adalah kondisi ketika jantung mengalami gangguan. Bentuk gangguan itu sendiri bisa
            bermacam-macam. Ada gangguan pada pembuluh darah jantung, irama jantung, katup jantung, atau gangguan
            akibat bawaan lahir.
        </p>
        <p>
            Jantung adalah otot yang terbagi menjadi empat ruang. Dua ruang terletak di bagian atas, yaitu atrium
            (serambi) kanan dan kiri. Sedangkan dua ruang lagi terletak di bagian bawah, yaitu ventrikel (bilik)
            kanan dan kiri. Antara ruang kanan dan kiri dipisahkan oleh dinding otot (septum) yang berfungsi
            mencegah tercampurnya darah yang kaya oksigen dengan darah yang miskin oksigen.
        </p>
        <p>Sumber: <a href="https://www.alodokter.com/penyakit-jantung">Aldodokter</a></p>
        <div class="row">
            <div class="6u 12u$(small)">
                <h3>Jenis penyakit jantung</h3>
                <p>
                    Ada beberapa jenis penyakit jantung, antara lain
                </p>
                <dl>
                    <dt>Penyakit jantung koroner</dt>
                    <dd>
                        <p>Merupakan suatu penyakit jantung yang terjadi akibat penyempitan pembuluh darah di jantung.</p>
                    </dd>
                    <dt>Penyakit jantung bawaan</dt>
                    <dd>
                        <p>Penyakit jantung bawaan, merupakan suatu masalah jantung yang ditemukan sejak bayi, yang paling umum ditemukan adalah kebocoran katup jantung.</p>
                    </dd>
                    <dt>Infeksi jantung (endokarditis)</dt>
                    <dd>
                        <p>Infeksi jantung (endokarditis), merupakan suatu infeksi pada lapisan dalam jantung.
                            Gagal jantung, merupakan suatu kegagalan otot jantung untuk memompakan darah secara memadai ke seluruh tubuh.</p>
                    </dd>
                    <dt>Aritmia</dt>
                    <dd>
                        <p>Aritmia, merupakan suatu gangguan irama jantung yang menyebabkan denyut jantung tidak normal.</p>
                    </dd>
                </dl>
                <p>Sumber: <a href="https://www.halodoc.com/kesehatan/penyakit-jantung">Halodoc</a></p>
            </div>
            <div class="6u$ 12u$(small)">
                <h3>Pencegahan</h3>
                <p>Pada penyakit jantung bawaan, upaya pencegahan yang efektif belum ditemukan hingga saat ini. Namun demikian, pada penyakit jantung koroner, gagal jantung, dan aritmia, beberapa upaya pencegahan dapat dilakukan, antara lain:</p>
                <ul class="alt">
                    <li>Mengonsumsi makanan tinggi serat, rendah gula, dan rendah lemak.</li>
                    <li>Menghentikan kebiasaan merokok dan menghindari paparan asap rokok.</li>
                    <li>Memeriksa tekanan darah, gula darah, dan kolesterol secara berkala.</li>
                    <li>Melakukan latihan fisik, seperti jogging, bersepeda, dan berenang, setidaknya 30 menit setiap hari.</li>
                </ul>
                <p>Sumber: <a href="https://www.halodoc.com/kesehatan/penyakit-jantung">Halodoc</a></p>
            </div>

        </div>

    </div>

</section>
{% endblock %}

corpe/templates/main/petunjuk.html
{% extends "layouts/base-sub.html" %}
{% block title %} {{ title }} {% endblock %}

{% block content %}
    <!-- Main -->
    <section id="main" class="wrapper">
        <div class="inner">
            <header class="align-center">
                <h2>Petunjuk penggunaan</h2>
                <p>Penggunaan aplikasi prediksi penyakit jantung koroner</p>
            </header>

            <!-- Intro -->
            <div class="row">
                <section class="6u 12u$(medium)">
                    <h2>Bagaimana?</h2>
                    <p><strong>Pengguna</strong> harus mengisikan data kesehatan yang dimiliki melalui form pada <a
                            href="{{ url_for('predict.predict') }}">Halaman ini</a>. Data yang diisikan haruslah benar dan tepat agar
                        didapatkan hasil prediksi yang baik. Detail pengisian ada di bawah ini.</p>
                </section>
                <section class="6u 12u$(medium) ">
                    <h3>Informasi</h3>
                    <p>Data kesehatan yang dimasukkan akan disimpan di basis data sistem untuk pengembangan
                        akurasi sistem prediksi tanpa menyebarluaskan data dan identitas pemilik data.</p>
                </section>
            </div>

            <hr class="major" />
            <h4>Data yang dimasukkan</h4>
            <dl>
                <dt>Usia</dt>
                <dd>
                    <p>Usia pasien saat memasukkan data.</p>
                </dd>
                <dt>Jenis kelamin</dt>
                <dd>
                    <p>Jenis kelamin pasien, laki-laki/perempuan.</p>
                </dd>
                <dt>Jenis nyeri pada dada</dt>
                <dd>
                    <p>Jenis nyeri pada dada. <strong>Angina</strong> adalah jenis nyeri
                        pada dada ketika otot dada tidak mendapat cukup oksigen.</p>
                </dd>
                <dt>Tekanan darah istirahat saat istirahat</dt>
                <dd>
                    <p>Tekanan darah pasien ketika tidak beraktifitas
                        atau dalam masa istirahat.</p>
                </dd>
                <dt>Kolesterol dalam mg/dl</dt>
                <dd>
                    <p>Kadar kolesterol dalam satuan miligram per desiliter</p>
                </dd>
                <dt>Kadar gula darah > 120 mg/dl</dt>
                <dd>
                    <p>Kadar gula darah, jika lebih dari 120 mg/dl.</p>
                </dd>
                <dt>Hasil tes elektrokardiografi saat istirahat</dt>
                <dd>
                    <p>Hasil tes
                        elektrokardiografi ketika pasien istirahat.</p>
                </dd>
                <dt>Hasil tes elektrokardiografi saat istirahat</dt>
                <dd>
                    <p>Hasil tes
                        elektrokardiografi ketika pasien istirahat.</p>
                    <ul class="alt">
                        <li>Normal.</li>
                        <li>Having ST-T: Memiliki kelainan gelombang ST-T 
                            (inversi gelmbang T dan elevasi atau depresi ST > 0.05 mV).</li>
                        <li>Menunjukkan hipertrofi ventrikel kiri yang mungkin atau 
                            pasti dengan kriteria estes.</li>
                    </ul>
                </dd>
                <dt>Denyut jantung maksimum.</dt>
                <dd>
                    <p>Denyut jantung maksimum yang dicapai pasien.</p>
                </dd>
                <dt>Nyeri saat beraktifitas.</dt>
                <dd>
                    <p>Nyeri yang dialami pasien saat berolahraga.</p>
                </dd>
                <dt>Depresi ST saat beraktifitas.</dt>
                <dd>
                    <p>Penurunan ST saat beraktifitas dalam nilai desimal. ST adalah.</p>
                </dd>
                <dt>Kemiringan puncak ST saat beraktifitas</dt>
                <dd>
                    <p>Kemiringan puncak ST saat beraktifitas</p>
                    <ul class="alt">
                        <li>Upsloping: menanjak.</li>
                        <li>Flat: data.</li>
                        <li>Downsloping: miring ke bawah.</li>
                    </ul>
                </dd>
                <dt>Pembuluh darah terdeteksi</dt>
                <dd>
                    <p>Banyaknya pembuluh darah yang diwarnai 
                        melalui Fluoroscopy</p>
                </dd>
                <dt>Pemeriksaan thalassemia</dt>
                <dd>
                    <p></p>
                    <ul class="alt">
                        <li>Normal: normal.</li>
                        <li>Fixed Defect: cacat tetap.</li>
                        <li>Reversable Defect: cacat yang dapat dikembalikkan.</li>
                    </ul>
                </dd>
            </dl>
        </div>

    </section>
{% endblock %}

corpe/templates/main/tentang.html
{% extends "layouts/base-sub.html" %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<section id="main" class="wrapper">
	<div class="inner">
		<header class="align-center">
			<h2>Tentang</h2>
			<p>Sekilas tentang</p>
		</header>

		<!-- Intro -->
		<div class="row">
			<section class="6u 12u$(medium)">
				<h2>Sistem Prediksi</h2>
				<p>
					Sistem prediksi penyakit jantung koroner berbasis website ini dibangun guna membangun kesadaran
					kesehatan jantung dan melakukan pencegahan dini serta segera melakukan perawatan jika terindikasi
					memiliki penyakit jantung
				</p>
			</section>
			<section class="6u 12u$(medium)">
				<h2>Untuk</h2>
				<ul class="alt">
					<li>Masyarakat umum</li>
					<li>Dokter</li>
					<li>Mahasiswa kedokteran</li>
				</ul>
			</section>
		</div>
	</div>

	</div>

</section>
{% endblock %}